### ISSUE TITLE
Sparse Tensor Creation in Hough Voting

### ISSUE THREAD

**Issue by Leerw** [POSTECH-CVLab/DHVR#4]
Hi, thank you for your impressive work!
I am confusing about the sparse tensor creation in hough voting, https://github.com/POSTECH-CVLab/DHVR/blob/master/src/dhvr.py#L94

```
coord = torch.cat(
            [
                torch.zeros(r_coord.shape[0]).unsqueeze(1).to(self.device),
                r_coord,
                t_coord,
            ],
            dim=1,
        )
```

why are zeros inserted in the COO?

**Comment by junha-l** [comment]
Hi, @Leerw 

The first dimension of sparse tensor coordinates is reserved for batch dimension, so if we want to represent `D` dimensional sparse tensor, the coordinates should be `D + 1` dimensional matrices.

As you can find in https://github.com/POSTECH-CVLab/DHVR/blob/f51578eaff706d2bd1a7a9b937fedf500343f790/src/dhvr.py#L112
the batch indices are removed to retrieve the actual 6D parameters.

**Comment by Leerw** [comment]
@junha-l  Thanks for your kind and quick reply!
